import React from 'react';

function Privacy() {
  return (
    <section className="section section-secondary">
      <div className="section-content">
        <h2>Privacy Policy</h2>
<main class="container">

    <article class="content">
      <span class="updated">Last updated: October 28, 2024</span>

      <section id="intro">
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p>
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </section>

      <section id="interpretation">
        <h2>Interpretation and Definitions</h2>

        <h3>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>

        <div class="definition-list">
          <div class="definition-item"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</div>
          <div class="definition-item"><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</div>
          <div class="definition-item"><strong>Company</strong> referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement refers to CodePRO LK, No 2/3, Hospital Junction, Polonnaruwa, Sri Lanka.</div>
          <div class="definition-item"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing details of Your browsing history on that website among its many uses.</div>
          <div class="definition-item"><strong>Country</strong> refers to Sri Lanka.</div>
          <div class="definition-item"><strong>Device</strong> means any device that can access the Service such as a computer, cellphone or digital tablet.</div>
          <div class="definition-item"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</div>
          <div class="definition-item"><strong>Service</strong> refers to the Website.</div>
          <div class="definition-item"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</div>
          <div class="definition-item"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</div>
          <div class="definition-item"><strong>Website</strong> refers to CodePRO LK, accessible from <a href="https://codeprolk.com" target="_blank" rel="noopener noreferrer">https://codeprolk.com</a>.</div>
          <div class="definition-item"><strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.</div>
        </div>
      </section>

      <section id="data-collected">
        <h2>Collecting and Using Your Personal Data</h2>

        <h3>Types of Data Collected</h3>

        <h3>Personal Data</h3>
        <p>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.
        </p>
        <p>Personally identifiable information may include, but is not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h3>Usage Data</h3>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as Your Device’s Internet Protocol address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p>
          When You access the Service by or through a mobile device, We may collect certain information automatically, including the type of mobile device You use, Your mobile device unique ID, IP address, mobile operating system, mobile Internet browser type, unique device identifiers and other diagnostic data.
        </p>
        <p>
          We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
        </p>
      </section>

      <section id="cookies">
        <h2>Tracking Technologies and Cookies</h2>
        <p>
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags and scripts to collect and track information and to improve and analyze Our Service.
        </p>

        <h3>Cookies or Browser Cookies</h3>
        <p>
          A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
        </p>

        <h3>Web Beacons</h3>
        <p>
          Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.
        </p>

        <p>
          Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
        </p>

        <h3>Types of Cookies We Use</h3>

        <div class="cookie-box">
          <strong>Necessary / Essential Cookies</strong><br />
          Type: Session Cookies<br />
          Administered by: Us<br />
          Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.
        </div>

        <div class="cookie-box">
          <strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
          Type: Persistent Cookies<br />
          Administered by: Us<br />
          Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
        </div>

        <div class="cookie-box">
          <strong>Functionality Cookies</strong><br />
          Type: Persistent Cookies<br />
          Administered by: Us<br />
          Purpose: These Cookies allow us to remember choices You make when You use the Website, such as login details or language preference.
        </div>
      </section>

      <section id="use">
        <h2>Use of Your Personal Data</h2>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account and registration as a user of the Service.</li>
          <li>For the performance of a contract related to products, items or services You have purchased.</li>
          <li>To contact You by email, telephone calls, SMS or other equivalent forms of electronic communication.</li>
          <li>To provide You with news, special offers and general information about goods, services and events similar to those You have purchased or enquired about unless You have opted not to receive such information.</li>
          <li>To manage Your requests to Us.</li>
          <li>For business transfers such as merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of assets.</li>
          <li>For other purposes such as data analysis, identifying usage trends, determining promotional campaign effectiveness and improving Our Service, products, services, marketing and Your experience.</li>
        </ul>
      </section>

      <section id="sharing">
        <h2>Sharing Your Personal Data</h2>
        <p>We may share Your personal information in the following situations:</p>
        <ul>
          <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service, or to contact You.</li>
          <li><strong>For business transfers:</strong> In connection with, or during negotiations of, any merger, sale of Company assets, financing or acquisition.</li>
          <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates and require those affiliates to honor this Privacy Policy.</li>
          <li><strong>With business partners:</strong> To offer You certain products, services or promotions.</li>
          <li><strong>With other users:</strong> When You share personal information or interact in public areas, such information may be viewed by all users and publicly distributed outside.</li>
          <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
        </ul>
      </section>

      <section id="retention">
        <h2>Retention of Your Personal Data</h2>
        <p>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with legal obligations, resolve disputes and enforce legal agreements and policies.
        </p>
        <p>
          The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when used to strengthen security, improve functionality or meet legal obligations.
        </p>
      </section>

      <section id="transfer">
        <h2>Transfer of Your Personal Data</h2>
        <p>
          Your information, including Personal Data, is processed at the Company’s operating offices and in other places where the parties involved in processing are located. This means information may be transferred to and maintained on computers located outside Your jurisdiction where data protection laws may differ.
        </p>
        <p>
          Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
        </p>
        <p>
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
        </p>
      </section>

      <section id="delete">
        <h2>Delete Your Personal Data</h2>
        <p>
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        </p>
        <p>
          Our Service may give You the ability to delete certain information about You from within the Service.
        </p>
        <p>
          You may update, amend or delete Your information at any time by signing in to Your Account, if You have one, and visiting the account settings section. You may also contact Us to request access to, correct or delete personal information that You have provided to Us.
        </p>
        <p>
          Please note that We may need to retain certain information when We have a legal obligation or lawful basis to do so.
        </p>
      </section>

      <section id="disclosure">
        <h2>Disclosure of Your Personal Data</h2>

        <h3>Business Transactions</h3>
        <p>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </p>

        <h3>Law Enforcement</h3>
        <p>
          Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.
        </p>

        <h3>Other Legal Requirements</h3>
        <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
      </section>

      <section id="security">
        <h2>Security of Your Personal Data</h2>
        <p>
          The security of Your Personal Data is important to Us, but no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>
      </section>

      <section id="children">
        <h2>Children’s Privacy</h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
        </p>
        <p>
          If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
        </p>
        <p>
          If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.
        </p>
      </section>

      <section id="links">
        <h2>Links to Other Websites</h2>
        <p>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third-party site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.
        </p>
      </section>

      <section id="changes">
        <h2>Changes to this Privacy Policy</h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let You know via email and/or a prominent notice on Our Service prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when posted on this page.
        </p>
      </section>

      <section id="contact">
        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>

        <div class="contact-card">
          <strong>Website:</strong> CodePRO LK
        </div>
      </section>
    </article>
  </main>
      </div>
    </section>
  );
}

export default Privacy;
